<?php
include('includes/components/html.php');
include('includes/dal/base.php');
include('includes/dal/country.php');
include('includes/dal/city.php');
include('includes/dal/unit.php');
include('includes/dal/category.php');
include('includes/dal/brand.php');
include('includes/dal/status.php');
include('includes/dal/users.php');
include('includes/dal/paymentMethod.php');
include('includes/dal/product.php');
include('includes/dal/productImage.php');
include('includes/dal/productLike.php');
include('includes/dal/productComment.php');
include('includes/dal/purchase.php');
include('includes/dal/purchaseDetails.php');
include('includes/dal/purchaseStatus.php');
?>